package com.ligeng.mapper.nochange;

import com.ligeng.entity.nochange.Mytb2;
import com.ligeng.entity.nochange.Mytb2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMytb2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int countByExample(Mytb2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int deleteByExample(Mytb2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int insert(Mytb2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int insertSelective(Mytb2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    List<Mytb2> selectByExample(Mytb2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    Mytb2 selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Mytb2 record, @Param("example") Mytb2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Mytb2 record, @Param("example") Mytb2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mytb2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytb2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mytb2 record);
}